language: node_js
node_js:
  - "6"
env:
  global:
    - BIN="node"
  matrix:
    -
    - BIN="phantomjs"
    - BIN="ringo"
matrix:
  include:
    - node_js: "0.10"
      env:
    - node_js: "0.12"
      env:
    - node_js: "4"
      env:
    - node_js: "5"
      env:
git:
  depth: 10
branches:
  only:
    - master
before_install:
  - "nvm use $TRAVIS_NODE_VERSION"
  - "npm set loglevel error"
  - "npm set progress false"
  - "npm i -g npm@\"^2.0.0\""
  - "[ $BIN != 'ringo' ] || (wget https://github.com/ringo/ringojs/releases/download/v0.11.0/ringojs-0.11.zip && sudo unzip ringojs-0.11 -d /opt && rm ringojs-0.11.zip)"
  - "[ $BIN != 'ringo' ] || (sudo ln -s /opt/ringojs-0.11/bin/ringo /usr/local/bin/ringo && sudo chmod +x /usr/local/bin/ringo)"
script:
  - "cd test && $BIN ./test.js"
